#!/usr/bin/env python3
"""
generate_earnings_pdf.py — Markdown → PDF for Quarterly Earnings Reports

Converts earnings analysis Markdown files into professional PDFs
with Kasona branding, company logos (from EODHD), and fixed table rendering.

Usage:
    python3 generate_earnings_pdf.py beiersdorf_q4_fy2025_earnings.md --ticker BEI.XETRA
    python3 generate_earnings_pdf.py <markdown_file> --ticker <SYMBOL.EXCHANGE>

Dependencies:
    pip3 install fpdf2 requests Pillow
"""

import argparse
import html
import os
import re
import sys
import tempfile
import urllib.request
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

# ============================================================
# Konfiguration
# ============================================================

# Unicode font path (Windows)
UNICODE_FONT_DIR = "C:/Windows/Fonts/"
UNICODE_FONT_REGULAR = "consola.ttf"
UNICODE_FONT_BOLD = "consolab.ttf"
UNICODE_FONT_ITALIC = "consolai.ttf"
UNICODE_FONT_BOLD_ITALIC = "consolaz.ttf"

# Colors (RGB) — Monochromatic Professional (Blue/Gray/Black)
COLOR_PRIMARY_BLUE = (30, 58, 138)        # #1E3A8A — Primary Brand Blue
COLOR_KASONA_DARK = (15, 23, 42)          # #0f172a — Deep slate
COLOR_DARK = (15, 23, 42)                 # Black
COLOR_PRIMARY = (30, 58, 138)             # Blue for h2
COLOR_ACCENT = (51, 65, 85)               # #334155 — Slate-600
COLOR_TEXT = (15, 23, 42)                 # Black
COLOR_LIGHT_BG = (248, 250, 252)         # Very light gray/blue
COLOR_BORDER = (203, 213, 225)           # Light gray/blue border
COLOR_MUTED = (100, 116, 139)            # Muted gray
COLOR_WHITE = (255, 255, 255)
COLOR_TABLE_HEADER = (15, 23, 42)        # Deep black for tables
COLOR_COVER_BG = (15, 23, 42)           # Deep black cover
COLOR_KASONA_ORANGE = (243, 108, 33)     # #F36C21 — Kasona Orange

# Font family name
FONT = "Consolas"

# Lines to skip from markdown (internal metadata — NEVER expose to clients)
SKIP_PATTERNS = [
    re.compile(r'^[\*_]*Disclaimer[:\*_]', re.IGNORECASE),
    re.compile(r'Generated by Kasona', re.IGNORECASE),
    re.compile(r'Rule of 3', re.IGNORECASE),
    re.compile(r'Word count[:\s]', re.IGNORECASE),
    re.compile(r'\beodhd\b', re.IGNORECASE),
    re.compile(r'\bpython\b', re.IGNORECASE),
    re.compile(r'\bscript[:\s]', re.IGNORECASE),
    re.compile(r'^Quarter:.*Analyst:.*$'),
    re.compile(r'^\*\*Quarter:\*\*.*Analyst:.*$'),
    re.compile(r'^Quartal:.*Analyst:.*$'),
    re.compile(r'^\*\*Quartal:\*\*.*Analyst:.*$'),
]


def strip_emoji(text):
    """Remove emoji and other non-BMP characters."""
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U0001F900-\U0001F9FF"
        "\U0001FA00-\U0001FA6F"
        "\U0001FA70-\U0001FAFF"
        "\U00002702-\U000027B0"
        "\U0000FE00-\U0000FE0F"
        "\U0000200D"
        "\U00002640-\U00002642"
        "\U00002600-\U000026FF"
        "\U0000231A-\U0000231B"
        "\U00002934-\U00002935"
        "\U000025AA-\U000025AB"
        "\U000025FB-\U000025FE"
        "\U000023E9-\U000023F3"
        "\U000023CF"
        "\U00002B05-\U00002B07"
        "\U00002B1B-\U00002B1C"
        "\U00002B50"
        "\U00002B55"
        "\U00003030"
        "\U0000303D"
        "\U00003297"
        "\U00003299"
        "]+", flags=re.UNICODE
    )
    return emoji_pattern.sub('', text)


def clean_text(text, strip_links=True):
    """Clean markdown formatting from text for plain display."""
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'`(.+?)`', r'\1', text)
    if strip_links:
        text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)
    text = html.unescape(text)
    text = strip_emoji(text)
    return text.strip()


def is_bold(text):
    return '**' in text


def should_skip_line(line):
    """Check if a line should be skipped (internal metadata)."""
    stripped = line.strip()
    for pattern in SKIP_PATTERNS:
        if pattern.match(stripped):
            return True
    return False


def download_company_logo(ticker, output_dir):
    """Download company logo from EODHD. Returns path or None."""
    parts = ticker.split(".")
    if len(parts) != 2:
        print(f"  [WARN] Invalid ticker format: {ticker} — expected SYMBOL.EXCHANGE")
        return None
    
    symbol, exchange = parts[0], parts[1]
    logo_path = os.path.join(output_dir, f"{symbol.lower()}_company_logo.png")

    # If logo already exists locally, use it
    if os.path.exists(logo_path):
        print(f"  [OK] Using local company logo: {logo_path}")
        return logo_path
    
    url = f"https://eodhistoricaldata.com/img/logos/{exchange}/{symbol}.png"
    
    try:
        urllib.request.urlretrieve(url, logo_path)
        size = os.path.getsize(logo_path)
        if size < 100:
            os.remove(logo_path)
            print(f"  [WARN] Logo too small ({size}B), likely not available")
            return None
        return logo_path
        print(f"  [OK] Company logo downloaded: {logo_path} ({size}B)")
        return logo_path
    except Exception as e:
        print(f"  [WARN] Could not download logo: {e}")
        return None


class EarningsReportPDF(FPDF):
    """Custom PDF class with Kasona branding and Unicode support."""

    def __init__(self, title="Earnings Report", kasona_logo=None, company_logo=None,
                 company_name="", quarter_info=""):
        super().__init__()
        self.report_title = title
        self.today = datetime.now().strftime("%d.%m.%Y")
        self.kasona_logo_path = kasona_logo
        self.company_logo_path = company_logo
        self.company_name = company_name
        self.quarter_info = quarter_info
        self.is_cover_page = True
        self._register_unicode_fonts()
        self.set_auto_page_break(auto=True, margin=25)

    def _register_unicode_fonts(self):
        """Register Arial Unicode TTF fonts."""
        font_dir = UNICODE_FONT_DIR
        self.add_font(FONT, "", os.path.join(font_dir, UNICODE_FONT_REGULAR))
        self.add_font(FONT, "B", os.path.join(font_dir, UNICODE_FONT_BOLD))
        self.add_font(FONT, "I", os.path.join(font_dir, UNICODE_FONT_ITALIC))
        self.add_font(FONT, "BI", os.path.join(font_dir, UNICODE_FONT_BOLD_ITALIC))

    def header(self):
        # Skip header on cover page
        if self.is_cover_page:
            return
        if self.page_no() > 1:
            # Top accent line
            self.set_draw_color(*COLOR_PRIMARY_BLUE)
            self.set_line_width(1.0)
            self.line(self.l_margin, 8, self.w - self.r_margin, 8)

            # Company/Kasona header text
            self.set_font(FONT, "I", 7)
            self.set_text_color(*COLOR_MUTED)
            self.set_y(10)
            self.cell(0, 5, f"KASONA — {self.company_name} Earnings Analysis", align="L")
            
            # Kasona logo in header (small)
            if self.kasona_logo_path and os.path.exists(self.kasona_logo_path):
                try:
                    self.image(self.kasona_logo_path, x=self.w - 35, y=5, h=6)
                except Exception:
                    pass
            self.ln(5)

    def footer(self):
        # Skip footer on cover page
        if self.is_cover_page:
            return
        self.set_y(-20)
        # Bottom line
        self.set_draw_color(*COLOR_PRIMARY_BLUE)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(2)
        self.set_font(FONT, "I", 7)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 5, f"Generated on {self.today} | KASONA Quarterly Earnings Analyst", align="L")
        # FIXED: Only show current page number
        self.cell(0, 5, f"Page {self.page_no()}", align="R")

    def render_cover_page(self):
        """Create a professional cover page with logos."""
        self.is_cover_page = True
        self.add_page()
        
        # ── Dark top section (smaller) ──
        dark_height = 95
        self.set_fill_color(*COLOR_COVER_BG)
        self.rect(0, 0, self.w, dark_height, 'F')
        
        # Title label
        self.set_y(25)
        self.set_font(FONT, "", 10)
        self.set_text_color(*COLOR_PRIMARY_BLUE)
        self.cell(0, 6, "QUARTERLY EARNINGS ANALYSIS", align="C")
        self.ln(10)
        
        # Company name (big, centered, white)
        self.set_font(FONT, "B", 24)
        self.set_text_color(*COLOR_WHITE)
        title_clean = clean_text(self.report_title)
        title_clean = re.sub(r'^Earnings Briefing:\s*', '', title_clean)
        self.multi_cell(0, 12, title_clean, align="C")
        
        # ── White section below dark area ──
        
        # Company logo (centered)
        logo_y = dark_height + 8
        effective_logo_path = self.company_logo_path if self.company_logo_path and os.path.exists(self.company_logo_path) else self.kasona_logo_path
        
        if effective_logo_path and os.path.exists(effective_logo_path):
            try:
                logo_h = 28
                from PIL import Image as PILImage
                img = PILImage.open(effective_logo_path)
                aspect = img.width / img.height
                logo_w = logo_h * aspect
                logo_x = (self.w - logo_w) / 2
                self.image(effective_logo_path, x=logo_x, y=logo_y, h=logo_h)
            except Exception:
                pass
        
        # Report metadata
        self.set_y(logo_y + 35)
        self.set_text_color(*COLOR_TEXT)
        self.set_font(FONT, "", 9)
        self.cell(0, 6, f"Report created on: {self.today}", align="C")
        self.ln(5)
        
        # Data sources specifically REMOVED per institutional guidelines
        self.set_font(FONT, "", 8)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 4, "Institutional Portfolio Analysis", align="C")
        self.ln(8)
        
        # Kasona logo (centered)
        if self.kasona_logo_path and os.path.exists(self.kasona_logo_path):
            try:
                kasona_h = 14
                from PIL import Image as PILImage
                img = PILImage.open(self.kasona_logo_path)
                aspect = img.width / img.height
                kasona_w = kasona_h * aspect
                kasona_x = (self.w - kasona_w) / 2
                self.image(self.kasona_logo_path, x=kasona_x, y=self.get_y(), h=kasona_h)
            except Exception:
                pass
        
        # Disclaimer box at bottom
        self.set_y(230)
        self.set_fill_color(*COLOR_LIGHT_BG)
        self.set_draw_color(*COLOR_BORDER)
        self.set_font(FONT, "I", 6.5)
        self.set_text_color(*COLOR_MUTED)
        disclaimer = (
            "This report was automatically generated using Artificial Intelligence by the "
            "KASONA Quarterly Earnings Analyst. It is intended for informational purposes "
            "only and does not constitute investment advice. Despite integration with "
            "institutional data providers and primary sources, all information should "
            "be independently verified before making any trading decisions. All data "
            "originates from publicly available sources."
        )
        x = self.l_margin + 10
        self.set_x(x)
        w = self.w - self.l_margin - self.r_margin - 20
        self.multi_cell(w, 3.5, disclaimer, fill=True, align="C")
        
        self.is_cover_page = False

    def render_last_page(self):
        """Create a professional last page with Kasona branding and disclaimer."""
        self.add_page()
        self.set_y(60)
        
        # Logo in center
        if self.kasona_logo_path and os.path.exists(self.kasona_logo_path):
            try:
                logo_h = 25
                from PIL import Image as PILImage
                img = PILImage.open(self.kasona_logo_path)
                aspect = img.width / img.height
                logo_w = logo_h * aspect
                logo_x = (self.w - logo_w) / 2
                self.image(self.kasona_logo_path, x=logo_x, y=self.get_y(), h=logo_h)
                self.ln(logo_h + 10)
            except Exception:
                self.ln(10)
        
        # A Kasona Production
        self.set_font(FONT, "B", 18)
        self.set_text_color(*COLOR_KASONA_DARK)
        self.cell(0, 10, "KASONA INSTITUTIONAL AUDIT", align="C")
        self.ln(12)
        
        # Auditor Sign-off
        self.set_font(FONT, "B", 11)
        self.set_text_color(*COLOR_PRIMARY_BLUE)
        self.cell(0, 10, "Senior Strategic Analyst & Governance Auditor", align="C")
        self.ln(8)
        
        # Certification
        self.set_font(FONT, "", 9)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 8, "This report has been audited for compliance with the Kasona Institutional Standard.", align="C")
        self.ln(6)
        self.cell(0, 8, f"Final Verification Date: {self.today}", align="C")
        self.ln(15)
        
        # Website Link
        self.set_font(FONT, "B", 11)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(0, 8, "www.kasona.ai", align="C", link="https://www.kasona.ai/")
        self.ln(40)
        
        # Final Legal Disclaimer block
        self.set_font(FONT, "I", 7)
        self.set_text_color(*COLOR_MUTED)
        disclaimer_text = (
            "Disclaimer: This report is synthesized using Artificial Intelligence and institutional data feeds. "
            "It is intended for professional use only and does not constitute financial or investment advice. "
            "All assertions regarding 'moats', 'resilience', and 'leadership' are qualitative analyst opinions "
            "based on the available data as of the verification date. Users should perform their own due diligence."
        )
        self.set_x(self.l_margin + 20)
        self.multi_cell(self.w - 40 - self.l_margin, 4, disclaimer_text, align="C")

    def write_rich_text(self, text, h=5, align="L"):
        """Render markdown text with bold and clickable hyperlinks."""
        # Clean text first from HTML entities and non-BMP
        text = html.unescape(text)
        text = strip_emoji(text)
        
        # Match [label](url) and **bold**
        # We split the text into parts and write them sequentially
        parts = re.split(r'(\*\*.*?\*\*|\[.*?\]\(.*?\))', text)
        
        orig_font_style = self.font_style
        orig_text_color = self.text_color
        
        for part in parts:
            if not part: continue
            
            if part.startswith('**') and part.endswith('**'):
                # Bold
                self.set_font(FONT, "B", self.font_size_pt)
                self.write(h, part[2:-2])
                self.set_font(FONT, "", self.font_size_pt)
            elif part.startswith('[') and '](' in part and part.endswith(')'):
                # Link
                match = re.match(r'\[(.*?)\]\((.*?)\)', part)
                if match:
                    label, url = match.groups()
                    self.set_text_color(*COLOR_ACCENT)
                    # We use underlining for links (we added 'U' as a dummy font mapping to regular)
                    # fpdf2 'write' handles underline if you use a style or manual underlining.
                    # Simplified: just blue text for now as hyperlinks are functional.
                    self.write(h, label, link=url)
                    self.set_text_color(*COLOR_TEXT)
            else:
                # Normal text
                self.write(h, part)
        
        # Reset styles
        self.set_font(FONT, orig_font_style, self.font_size_pt)
        self.set_text_color(*COLOR_TEXT)


def parse_table(lines, start_idx):
    """Parse a markdown table starting at start_idx. Returns (rows, end_idx)."""
    rows = []
    idx = start_idx
    while idx < len(lines):
        line = lines[idx].strip()
        if not line.startswith('|'):
            break
        if re.match(r'^\|[\s\-:|]+\|$', line):
            idx += 1
            continue
        cells = [c.strip() for c in line.split('|')[1:-1]]
        if cells:
            rows.append(cells)
        idx += 1
    return rows, idx


def render_table(pdf, rows):
    """Render a parsed markdown table."""
    if not rows:
        return

    header = rows[0]
    data = rows[1:]
    num_cols = len(header)
    effective_width = pdf.w - pdf.l_margin - pdf.r_margin

    col_widths = []
    for col_idx in range(num_cols):
        max_len = len(clean_text(header[col_idx]))
        for row in data:
            if col_idx < len(row):
                max_len = max(max_len, len(clean_text(row[col_idx])))
        col_widths.append(max(max_len, 3))

    total_chars = sum(col_widths) if sum(col_widths) > 0 else 1
    col_widths = [max(w / total_chars * effective_width, 12) for w in col_widths]
    total_width = sum(col_widths)
    if total_width > effective_width:
        scale = effective_width / total_width
        col_widths = [w * scale for w in col_widths]

    if pdf.get_y() + 15 > pdf.h - pdf.b_margin:
        pdf.add_page()

    pdf.set_x(pdf.l_margin)
    pdf.set_font(FONT, "B", 7.5)
    pdf.set_fill_color(*COLOR_TABLE_HEADER)
    pdf.set_text_color(*COLOR_WHITE)
    pdf.set_draw_color(*COLOR_TABLE_HEADER)
    
    header_height = 7
    for i, cell in enumerate(header):
        w = col_widths[i]
        cell_text = clean_text(cell)
        char_per_line = max(int(w / 2), 5)
        lines_needed = max(1, (len(cell_text) + char_per_line - 1) // char_per_line)
        header_height = max(header_height, lines_needed * 4 + 3)
    
    x_start = pdf.l_margin
    y_start = pdf.get_y()
    for i, cell in enumerate(header):
        w = col_widths[i]
        cell_text = clean_text(cell)
        pdf.set_xy(x_start + sum(col_widths[:i]), y_start)
        pdf.rect(x_start + sum(col_widths[:i]), y_start, w, header_height, 'DF')
        pdf.set_xy(x_start + sum(col_widths[:i]) + 1, y_start + 1)
        pdf.multi_cell(w - 2, 3.5, cell_text, align="L")
    
    pdf.set_xy(x_start, y_start + header_height)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.set_draw_color(*COLOR_BORDER)
    
    for row_idx, row in enumerate(data):
        fill_color = COLOR_LIGHT_BG if row_idx % 2 == 0 else COLOR_WHITE
        row_height = 6
        for i in range(num_cols):
            w = col_widths[i]
            cell_text = clean_text(row[i]) if i < len(row) else ""
            char_per_line = max(int((w - 2) / 1.8), 5)
            lines_needed = max(1, (len(cell_text) + char_per_line - 1) // char_per_line)
            row_height = max(row_height, lines_needed * 3.5 + 2)
        
        if pdf.get_y() + row_height > pdf.h - pdf.b_margin:
            pdf.add_page()
            pdf.set_x(pdf.l_margin)
        
        x_start = pdf.l_margin
        y_start = pdf.get_y()
        for i in range(num_cols):
            w = col_widths[i]
            cell_text = clean_text(row[i]) if i < len(row) else ""
            style = "B" if i < len(row) and is_bold(row[i]) else ""
            pdf.set_font(FONT, style, 7.5)
            pdf.set_fill_color(*fill_color)
            cell_x = x_start + sum(col_widths[:i])
            pdf.rect(cell_x, y_start, w, row_height, 'DF')
            pdf.set_xy(cell_x + 1, y_start + 1)
            pdf.multi_cell(w - 2, 3.5, cell_text, align="L")
        pdf.set_xy(x_start, y_start + row_height)
    pdf.ln(4)


def convert_md_to_pdf(md_path, output_dir, ticker=None, kasona_logo=None):
    """Convert a single Markdown earnings report to PDF with hyperlink support."""
    md_content = md_path.read_text(encoding="utf-8")
    lines = md_content.split("\n")

    title = md_path.stem
    for line in lines:
        if line.startswith("# "):
            title = clean_text(line[2:], strip_links=True)
            break
    
    quarter_info = ""
    for line in lines:
        if line.startswith("**Quartal:**") or "Report-Datum:" in line:
            quarter_info = clean_text(line)
            break

    company_name = title
    if ":" in company_name: company_name = company_name.split(":")[1].strip()
    if "(" in company_name: company_name = company_name.split("(")[0].strip()

    company_logo = download_company_logo(ticker, str(output_dir)) if ticker else None

    pdf = EarningsReportPDF(
        title=title, kasona_logo=kasona_logo,
        company_logo=company_logo, company_name=company_name,
        quarter_info=quarter_info
    )
    pdf.alias_nb_pages()
    pdf.render_cover_page()
    pdf.add_page()

    idx = 0
    in_code_block = False
    code_lines = []
    skip_first_h1 = True

    while idx < len(lines):
        line = lines[idx]
        stripped = line.strip()

        if should_skip_line(line):
            idx += 1
            continue

        if stripped.startswith("```"):
            if in_code_block:
                pdf.set_fill_color(*COLOR_LIGHT_BG)
                pdf.set_draw_color(*COLOR_BORDER)
                pdf.set_font(FONT, "", 7)
                w = pdf.w - pdf.l_margin - pdf.r_margin
                for cl in code_lines:
                    if pdf.get_y() + 4 > pdf.h - pdf.b_margin: pdf.add_page()
                    pdf.set_x(pdf.l_margin)
                    pdf.cell(w, 4, clean_text(cl), fill=True)
                    pdf.ln()
                pdf.ln(4)
                code_lines = []
                in_code_block = False
            else:
                in_code_block = True
            idx += 1
            continue

        if in_code_block:
            code_lines.append(line)
            idx += 1
            continue

        if not stripped:
            idx += 1
            continue

        # Headers
        if stripped.startswith("# ") and not stripped.startswith("## "):
            if skip_first_h1:
                skip_first_h1 = False
                idx += 1
                continue
            pdf.ln(6)
            pdf.set_font(FONT, "B", 16)
            pdf.set_text_color(*COLOR_DARK)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 8, clean_text(stripped[2:]))
            pdf.set_draw_color(*COLOR_PRIMARY_BLUE)
            pdf.set_line_width(0.8)
            pdf.line(pdf.l_margin, pdf.get_y() + 1, pdf.w - pdf.r_margin, pdf.get_y() + 1)
            pdf.ln(5)
            idx += 1
            continue

        if stripped.startswith("## "):
            pdf.ln(4)
            pdf.set_font(FONT, "B", 13)
            pdf.set_text_color(*COLOR_PRIMARY_BLUE)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 7, clean_text(stripped[3:]))
            pdf.set_draw_color(*COLOR_BORDER)
            pdf.line(pdf.l_margin, pdf.get_y() + 1, pdf.w - pdf.r_margin, pdf.get_y() + 1)
            pdf.ln(4)
            idx += 1
            continue

        if stripped.startswith("### "):
            pdf.ln(3)
            pdf.set_font(FONT, "B", 11)
            pdf.set_text_color(*COLOR_ACCENT)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, clean_text(stripped[4:]))
            pdf.ln(3)
            idx += 1
            continue

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            pdf.ln(3)
            pdf.set_draw_color(*COLOR_BORDER)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(5)
            idx += 1
            continue

        # Table
        if stripped.startswith("|"):
            pdf.set_x(pdf.l_margin)
            rows, new_idx = parse_table(lines, idx)
            if rows: render_table(pdf, rows)
            idx = new_idx
            continue

        # Blockquote
        if stripped.startswith("> "):
            quote_text = clean_text(stripped[2:], strip_links=False)
            while idx + 1 < len(lines) and lines[idx + 1].strip().startswith("> "):
                idx += 1
                quote_text += " " + clean_text(lines[idx].strip()[2:], strip_links=False)
            pdf.set_fill_color(*COLOR_LIGHT_BG)
            pdf.set_font(FONT, "I", 9)
            pdf.set_x(pdf.l_margin + 5)
            # Use write_rich_text for blockquotes if they have links
            pdf.write_rich_text(quote_text, h=5)
            pdf.ln(8) # Extra space after blockquote
            idx += 1
            continue

        # Lists with Hyperlink Support
        if stripped.startswith("- ") or stripped.startswith("* "):
            pdf.set_font(FONT, "", 9)
            pdf.set_text_color(*COLOR_TEXT)
            indent = len(line) - len(line.lstrip())
            bullet_indent = min(4 + (indent * 2), 20)
            text = stripped[2:]
            pdf.set_x(pdf.l_margin + bullet_indent)
            pdf.cell(4, 5, chr(8226))
            # Use write_rich_text for bullet point content
            pdf.write_rich_text(text, h=5)
            pdf.ln(6)
            idx += 1
            continue

        match = re.match(r'^(\d+)\.\s+(.+)', stripped)
        if match:
            pdf.set_font(FONT, "", 9)
            pdf.set_text_color(*COLOR_TEXT)
            num, text = match.group(1), match.group(2)
            pdf.set_x(pdf.l_margin)
            pdf.cell(8, 5, f"{num}.")
            pdf.write_rich_text(text, h=5)
            pdf.ln(6)
            idx += 1
            continue

        # Regular Paragraph with Hyperlink Support
        pdf.set_font(FONT, "", 9)
        pdf.set_text_color(*COLOR_TEXT)
        pdf.set_x(pdf.l_margin)
        pdf.write_rich_text(stripped, h=5)
        pdf.ln(8)
        idx += 1

    # Footer Disclaimer
    pdf.ln(10)
    pdf.set_draw_color(*COLOR_PRIMARY_BLUE)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)
    pdf.set_font(FONT, "I", 7)
    pdf.set_text_color(*COLOR_MUTED)
    # Last Page (Branding & Disclaimer)
    pdf.render_last_page()
    
    pdf_filename = md_path.stem + ".pdf"
    pdf_path = output_dir / pdf_filename
    pdf.output(str(pdf_path))
    return pdf_path


def main():
    parser = argparse.ArgumentParser(description="Earnings Markdown → PDF with Branding & Links")
    parser.add_argument("file", help="Markdown file to convert")
    parser.add_argument("--ticker", help="Company ticker SYMBOL.EXCHANGE")
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--kasona-logo", default=None)
    args = parser.parse_args()
    
    md_path = Path(args.file).resolve()
    if not md_path.exists(): sys.exit(1)

    output_dir = Path(args.output_dir) if args.output_dir else md_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    kasona_logo = args.kasona_logo
    if not kasona_logo:
        script_dir = Path(__file__).parent
        for ext in [".jpg", ".png", ".jpeg"]:
            candidate = script_dir / f"kasona_logo{ext}"
            if candidate.exists():
                kasona_logo = str(candidate)
                break

    try:
        pdf_path = convert_md_to_pdf(md_path, output_dir, args.ticker, kasona_logo)
        print(f"\n  [OK] {pdf_path.name}")
    except Exception as e:
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
